# Generated by Django 4.1.3 on 2022-11-23 19:32

import customers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default=customers.utils.Helper.reference_generator, max_length=30, unique=True),
        ),
    ]
