# Generated by Django 4.1.3 on 2022-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
